language: node_js
node_js:
  - "8"
dist: trusty
services: 
  - postgresql
addons:
  postgresql: "9.4"
env:
  global:
  - DB_USERNAME=postgres
  - DB_PASSWORD=postgres
  - DB_HOST=127.0.0.1
  - TEST_DATABASE=test_db
  - SESSION_SECRET=secret
before_script:
  - npm install
  - psql -c 'drop database if exists test_db;' -U postgres
  - psql -c 'create database test_db;' -U postgres
  - sequelize db:migrate --env test
cache: 
  directories: 
    - node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test